# -*- coding: utf-8 -*-
"""sementic_search

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MMxAVHEESZz83vBt7CSz5smqC9bfVKxq
"""

from langchain_huggingface import HuggingFaceEmbeddings
from dotenv import load_dotenv
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
from google.colab import userdata
import os
os.environ["HUGGINGFACEHUB_API_TOKEN"] = userdata.get("HUGGINGFACEHUB_API_TOKEN")

load_dotenv()
embedding = HuggingFaceEmbeddings(
    model_name="BAAI/bge-small-en-v1.5"

)



documents = [
    "Karachi is the largest city in Pakistan, known for its vibrant culture and coastal location.",
    "Lahore is famous for its historical landmarks, rich food culture, and lively atmosphere.",
    "Islamabad, the capital city of Pakistan, is known for its greenery and modern infrastructure.",
    "Peshawar is an ancient city known for its Pashtun heritage and traditional cuisine.",
    "Quetta, located in Balochistan, is famous for its cold weather, orchards, and rugged mountains."

]

query = 'tell me about Peshawar'

doc_embeddings = embedding.embed_documents(documents)
query_embedding = embedding.embed_query(query)

scores = cosine_similarity([query_embedding], doc_embeddings)[0]

index, score = sorted(list(enumerate(scores)),key=lambda x:x[1])[-1]

print(query)
print(documents[index])
print("similarity score is:", score)

!pip install --upgrade langchain-huggingface huggingface_hub python-dotenv sentence-transformers

